import Head from 'next/head'
import Image from 'next/image'
import { Inter, Nabla } from '@next/font/google'
import Layout from '@/components/Layout'
import LoginContent from '@/components/login/LoginContent'
import NavBarLayout from '@/components/Layout'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Ping Pong</title>
        <link href='https://fonts.googleapis.com/css?family=Baloo' rel='stylesheet'></link>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <div className="flex items-center  flex-wrap justify-center sm:justify-start">
      <Image 
            src="/game.png"
            alt='game'
            width={800}
            height={600}
          />
      <div className="ml-4 sm:ml-8 text-center sm:text-left">
        <h2 className="text-2xl font-bold">Pognitor</h2>
        <p className="text-gray-500 mt-2">Your text description goes here.</p>
      </div>
    </div> */}

        <div className="relative pt-12 bg-blueGray-50">
        <div className="items-center flex flex-wrap justify-center">
          <div className=" px-4">
          <Image 
            src="/game.png"
            alt='game'
            width={500}
            height={600}
          />
          </div>
          <div className="mt-4 sm:ml-8 text-center sm:text-left ">
              <h3 className="text-2xl font-bold text-white">Ponigator</h3>
              <p className="mt-4 text-lg leading-relaxed text-white ">
                  The Ultimate Exprerience For The Mighty Ping Context!
              </p>
              <div className='pt-5'>
                <button className=" uppercase mx-auto shadow
                bg-[#0097E2] hover:bg-indigo-700 focus:shadow-outline 
                focus:outline-none text-white text-s font-bold py-2 px-12 rounded-full">JOIN NOW</button>
              </div>

          </div>
        </div>
        </div>

        {/* <div classNameNameName="flex items-center justify-center h-screen flex-wrap">
          <Image 
            src="/game.png"
            alt='game'
            width={800}
            height={600}
          />
          <div classNameNameName="">
            <p>Ponigator</p>
            <p>The Ultimate Exprerience For The Mighty Ping Context!</p>
          </div>
        </div> */}
    </>
  ) 
}

Home.getLayout = function getLayout(page : React.ReactNode) {
  return (
    <NavBarLayout>
        {page}
    </NavBarLayout>
  )
}