import Head from 'next/head'
import Image from 'next/image'
import { Inter, Nabla } from '@next/font/google'
import Layout from '@/components/Layout'
import LoginContent from '@/components/login/LoginContent'
import NavBarLayout from '@/components/Layout'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Ping Pong</title>
        <link href='https://fonts.googleapis.com/css?family=Baloo' rel='stylesheet'></link>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div className="relative pt-12 bg-blueGray-50">
          <div className="items-center flex flex-col-reverse justify-center xl:flex-row gap-10">
            <div className=" px-4 shrink-0">
              <Image 
                src="/game.png"
                alt='game'
                width={700}
                height={600}
              />
            </div>

            <div className="text-center xl:text-left">
              <h3 className="text-3xl font-bold xl:text-4xl text-white mb-1 md:mb-10">Ponigator</h3>
              <p className="mt-4 text-xl xl:text-4xl md:text-3xl leading-relaxed mb-1 md:mb-10 break-words text-white ">
                  The Ultimate Exprerience For The Mighty Ping Context!
              </p>
              <div className='pt-5'>
                <button className=" uppercase mx-auto shadow bg-[#0097E2] hover:bg-[#2C3B7C] transform transition duration-300 
                  hover:text-l hover:scale-110  text-white text-s hover:text-l 
                  font-bold py-2 px-12 rounded-full">
                  JOIN NOW
                </button>
              </div>
            </div>
          </div>
      </div>

    </>
  ) 
}

Home.getLayout = function getLayout(page : React.ReactNode) {
  return (
    <NavBarLayout>
        {page}
    </NavBarLayout>
  )
}